[package]
name = "dusk-abi"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
ethereum-types = { version = "0.4", default-features = false }
serde = { version = "*", default-features = false }
ssmarshal = { version = "1.0", default-features = false }
