[package]
name = "dusk-abi"
version = "0.4.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

repository = "https://github.com/dusk-network/dusk-abi"
keywords = ["cryptography", "crypto", "pki", "bls12-381"]
categories =["cryptography", "cryptography::cryptocurrencies", "no-std", "wasm"]
description = "A library that holds the types and functions required to perform keys operations in Dusk"
license = "MPL-2.0"
exclude = [".github/workflows/ci.yml", ".gitignore"]

[dependencies]
cfg-if = "0.1"
canonical = "0.5"
canonical_derive = "0.5"
wee_alloc = "0.4"

[dev-dependencies]
canonical_fuzz = "0.5"
canonical_host = "0.5"
arbitrary = "0.3"

[features]
std = []
