[package]
name = "dusk-abi"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dependencies]
serde = { version = "*", default-features = false }
fermion = { version = "0.2", default-features = false }

[features]
default = ["std"]
std = ["fermion/std"]